Resources:
  ResourceLayer0FE6EC02:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content:
        S3Bucket:
          Ref: AssetParametersca413ce94bf17384623eb657ea57a5af5931b1cfd0ac66ae084ab4f378c3aa39S3BucketBFC2963E
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersca413ce94bf17384623eb657ea57a5af5931b1cfd0ac66ae084ab4f378c3aa39S3VersionKey262CBED4
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersca413ce94bf17384623eb657ea57a5af5931b1cfd0ac66ae084ab4f378c3aa39S3VersionKey262CBED4
      CompatibleRuntimes:
        - python3.8
      LayerName: resource_layer
      LicenseInfo: MIT
    Metadata:
      aws:cdk:path: InsiderStack/ResourceLayer/Resource
      aws:asset:path: S:\Repos\insider-alert\repos\resources
      aws:asset:property: Content
  RetrieveMoversServiceRoleDB2D1D5B:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
    Metadata:
      aws:cdk:path: InsiderStack/RetrieveMovers/ServiceRole/Resource
  RetrieveMovers3B5BF780:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters21b5f90b6c670da054f4c4f50e701fd5f2fa55576605fd996a2088cb46d70ca2S3Bucket3529BB34
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters21b5f90b6c670da054f4c4f50e701fd5f2fa55576605fd996a2088cb46d70ca2S3VersionKey9958CA57
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters21b5f90b6c670da054f4c4f50e701fd5f2fa55576605fd996a2088cb46d70ca2S3VersionKey9958CA57
      Handler: retrieve_movers.handler
      Role:
        Fn::GetAtt:
          - RetrieveMoversServiceRoleDB2D1D5B
          - Arn
      Runtime: python3.8
      Layers:
        - Ref: ResourceLayer0FE6EC02
    DependsOn:
      - RetrieveMoversServiceRoleDB2D1D5B
    Metadata:
      aws:cdk:path: InsiderStack/RetrieveMovers/Resource
      aws:asset:path: S:\Repos\insider-alert\repos\python
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.75.0,@aws-cdk/assets=1.75.0,@aws-cdk/aws-applicationautoscaling=1.75.0,@aws-cdk/aws-autoscaling-common=1.75.0,@aws-cdk/aws-cloudwatch=1.75.0,@aws-cdk/aws-codeguruprofiler=1.75.0,@aws-cdk/aws-ec2=1.75.0,@aws-cdk/aws-efs=1.75.0,@aws-cdk/aws-events=1.75.0,@aws-cdk/aws-iam=1.75.0,@aws-cdk/aws-kms=1.75.0,@aws-cdk/aws-lambda=1.75.0,@aws-cdk/aws-logs=1.75.0,@aws-cdk/aws-s3=1.75.0,@aws-cdk/aws-s3-assets=1.75.0,@aws-cdk/aws-sqs=1.75.0,@aws-cdk/aws-ssm=1.75.0,@aws-cdk/cloud-assembly-schema=1.75.0,@aws-cdk/core=1.75.0,@aws-cdk/cx-api=1.75.0,@aws-cdk/region-info=1.75.0,jsii-runtime=Python/3.9.0
    Metadata:
      aws:cdk:path: InsiderStack/CDKMetadata/Default
Parameters:
  AssetParametersca413ce94bf17384623eb657ea57a5af5931b1cfd0ac66ae084ab4f378c3aa39S3BucketBFC2963E:
    Type: String
    Description: S3 bucket for asset "ca413ce94bf17384623eb657ea57a5af5931b1cfd0ac66ae084ab4f378c3aa39"
  AssetParametersca413ce94bf17384623eb657ea57a5af5931b1cfd0ac66ae084ab4f378c3aa39S3VersionKey262CBED4:
    Type: String
    Description: S3 key for asset version "ca413ce94bf17384623eb657ea57a5af5931b1cfd0ac66ae084ab4f378c3aa39"
  AssetParametersca413ce94bf17384623eb657ea57a5af5931b1cfd0ac66ae084ab4f378c3aa39ArtifactHashCD3E5E07:
    Type: String
    Description: Artifact hash for asset "ca413ce94bf17384623eb657ea57a5af5931b1cfd0ac66ae084ab4f378c3aa39"
  AssetParameters21b5f90b6c670da054f4c4f50e701fd5f2fa55576605fd996a2088cb46d70ca2S3Bucket3529BB34:
    Type: String
    Description: S3 bucket for asset "21b5f90b6c670da054f4c4f50e701fd5f2fa55576605fd996a2088cb46d70ca2"
  AssetParameters21b5f90b6c670da054f4c4f50e701fd5f2fa55576605fd996a2088cb46d70ca2S3VersionKey9958CA57:
    Type: String
    Description: S3 key for asset version "21b5f90b6c670da054f4c4f50e701fd5f2fa55576605fd996a2088cb46d70ca2"
  AssetParameters21b5f90b6c670da054f4c4f50e701fd5f2fa55576605fd996a2088cb46d70ca2ArtifactHashB22B9BDB:
    Type: String
    Description: Artifact hash for asset "21b5f90b6c670da054f4c4f50e701fd5f2fa55576605fd996a2088cb46d70ca2"

